### ISSUE TITLE
[IndexOutOfBoundsException: Index: 4, Size: 4]

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#1]
http://drachten.informatik.uni-mannheim.de/link/dbpedia/thinker:t2474

Execution exception
[IndexOutOfBoundsException: Index: 4, Size: 4]
In /opt/lode/app/views/enhancers/link_entity.scala.html at line 42.
39                      }
40              } else {
41                  @for(i <- 0 to sparqlcontrollers.Setting.L_PROPERTIES-1) {
42                          @displayProperty(ec.getAttributes().get(i).getPropertyURI(), ec.getAttributes().get(i))
43                      }
44              }
45          </div>
46          }
47  </div>

**Comment by sztyler** [comment]
should be fixed in master a7a6350
