### ISSUE TITLE
Make tool tips for concept and property URIs clickable

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#12]
One of the advantages of RDF is that it makes each object dereferencable, that is, each URI can be entered into a browser to get a description of the entity. Of course, this is also true for concepts and properties. To allow users to better understand the properties offered in the repositories, the tool tips should be clickable URIs. For instance, the ObjectProperty "subject" with the URI http://purl.org/dc/terms/subject should have a tool tip with a clickable URI that leads the user to http://purl.org/dc/terms/subject.

**Comment by sztyler** [comment]
complete in rev. b27713e

-all tooltips are now clickable (explorer, enhancer, linker, entity overview, dialogs)
