### ISSUE TITLE
Browser: zeige etwas wenn man auf ein konzept klickt

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#14]
Jan: wenn man ohne etwas einzugeben auf ein konzept klickt, dann kommen alle instanzen zu dem konzept.. Denke, das wuerde den einstieg stark erleichtern.

Mathias: Das wuerde ich auch gerne umgesetzt sehen. Wichtig ist, dass man
generell mit limits und offsets arbeitet (und "more" Links) und evtl.
als Benutzer diesen limit einstellen kann.

Jan: oder man stellt auf so eine tabelle um, die mehrere seiten hat.

**Comment by jakob0910** [comment]
Ich habe damit begonnen, aber es gibt noch ein paar Probleme, die mehr oder weniger auch mit Issue #11 zusammenhängen. Aktuell habe ich mich für die Variante mit mehreren Seiten entschieden.

Habe noch keine gute Idee wie ich die Anzahl der Zeilen insgesamt am einfachsten bestimme und diese dann gleichmäßig auf die Seiten verteile. Nur mit offset und limit geht das wahrscheinlich nicht.

**Comment by mniepert** [comment]
Ich weiss nicht genau, was Du hier meinst. Ist es nicht moeglich einfach
einzustellen, dass es z.B. 50 Zeilen pro Seite gibt? Dann kann man asynchron
die ersten 50 Seiten laden, diese anzeigen und derweil im Hintergrund die
naechsten 50, usw.

2013/2/17 jakob0910 notifications@github.com

**Comment by jakob0910** [comment]
(Jan) Wir sitzen gerade an dem problem und ich habe es jetzt verstanden habe aber noch keine Lösung. Ich melde mich mit einer Lösung / Lösungsvorschlag.

**Comment by mniepert** [comment]
Looks much better now!

**Comment by jakob0910** [comment]
The initial issue of this ticket is solved. The remaining problems will be tracked in issue #11.
