### ISSUE TITLE
Beautify footer of site

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#15]
eine Bitte habe ich noch, fuer die neue Produktion-Server Version.
Koennt ihr bitte den Footer der Seite dem des InPhO Projekts aehneln
lassen?

https://inpho.cogs.indiana.edu/

Hier koennen wir statt einem Logo, drei nehmen (z.B.:)

http://www.cs.washington.edu/images/logo/CSElogoText_1000.jpg
http://en.wikipedia.org/wiki/File:Indiana_University_seal.svg
http://upload.wikimedia.org/wikipedia/commons/0/04/University_of_Mannheim.svg

Die Copyright information etc. mit "Trustees of bla" koennt ihr
weglassen. Es sollte aber einen Link nicht nur zu GitHub sondern auch
zur About page geben. Ware super, wenn das naechste Woche relativ hohe
Prioritaet bekaeme.

**Comment by jakob0910** [comment]
Ist das so ok?
![lode-footer](https://f.cloud.github.com/assets/3485169/164166/d35c33c6-787e-11e2-9481-b1ec63619515.PNG)

Ich habe für Mannheim ein anderes Logo genommen, da dann alle das gleiche Format haben.

**Comment by mniepert** [comment]
Ja, sieht klasse aus. Danke!
