### ISSUE TITLE
Three letters in search interface return list without name, concept, sameAs links filled in

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#16]
How to reproduce on current production system (lode.*):

Go to content interface http://lode.informatik.uni-mannheim.de/content
Type in three letters (for instance "tem"). A list of entities and thinkers is shown but the columns "name", "concepts", "sameAs Links" are not populated.

**Comment by sztyler** [comment]
Is this really a bug? - I mean - how long did you wait? - the columns "name", "concepts" and "sameAs Links" will loaded asynchronously - so if the search returned a lot of entry it can take some time if the columns are also loaded.

**Comment by mniepert** [comment]
I waited a looong time! :) Also, the numbers in the concept buttons are smaller than 100 (e.g., search term "her")

**Comment by jakob0910** [comment]
I will investigate this. There will be some changes when issue #14 is implemented.

**Comment by jakob0910** [comment]
I am not sure what caused this problem but it is not reproducible after I made some changes regarding the search interface.
