### ISSUE TITLE
Improve drag&drop of enhancer interface

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#18]
When dragging a datatype property the field "Add new _data_ property" should appear between the heading "Data properties" and above the area listing the existing data properties.

Same for object properties.

Use the heading Concepts instead of Concept, so that each section heading is in the plural.

When dragging a concept (e.g. Person) the field should read "Add new concept."

**Comment by sztyler** [comment]
fixed in revision [master 0bfd6df]
