### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by colinallen** [linkedhumanities/lode#19]
I had just linked one pair of ideas and got

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by sztyler** [comment]
please provide more information or urls - so that we can reproduce the problem.

(But I think that we restart the server during your try of linking something.)

**Comment by colinallen** [comment]
Indeed the problem went away so I think you are right that it was due to the server restart.

**Comment by sztyler** [comment]
closed
