### ISSUE TITLE
return to search results

### ISSUE THREAD

**Issue by colinallen** [linkedhumanities/lode#20]
If one has done a search for entities matching a particular string (e.g. "animal") and then gone ahead and linked one of them (e.g. "animal cognition") to the DBPedia entity, then there ought to be an easy way to get back to the previous search results to keep working on related ideas.

**Comment by sztyler** [comment]
add a back button in revision [master d76bfa1d] but it leads only to the content page - not to the previous search result (coming soon)

**Comment by jakob0910** [comment]
The search input (query, filter, page) gets saved in a cookie so that the search interface can be restored.
