### ISSUE TITLE
OWLIM-SE Installation as solution for many problems ;-)

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#22]
We now have several enhancement tickets where we need reasoning in SPARQL (e.g. the problem with same-as relations #11, #21). Future plans also require reasoning (e.g. restructuring concepts in search as trees, finding that plato is also an "entity" although its only marked as philosoph).

The solution could be OWLIM-SE (http://owlim.ontotext.com/display/OWLIMv42/OWLIM-SE+Reasoner)

I now continue in German because origninally I did not want to post it here:

ich glaube ich habe zumindest eine mögliche Lösung gefunden. Sie heißt owllim (http://owlim.ontotext.com/display/OWLIMv42/OWLIM-SE+Reasoner).

Im prinzip ist OWLlim ein Tool in dem man regeln definieren kann. Z.B. kann man sowas sagen wie:

Consistency: both_sameAs_and_differentFrom_is_forbidden
    x owl:sameAs y
    x owl:differentFrom y
    -------------------------------

Diese Regel sagt, dass sameAs und differentFrom niemals zusammen auftreten dürfen.
(Quelle: http://owlim.ontotext.com/display/OWLIMv42/OWLIM-SE+Reasoner)

Dies ist so ähnlich, wie das was ihr implementieren wolltet (wenn ich das richtig in erinnerung habe).

Nun gibt es vordefinierte Regelsätze für z.B. OWL 2 QL oder OWL 2 RL, so dass reasoning funktioniert. Sprich, wenn man fragt: "Plato rdf:type Entity" sollte unser "Plato" nun auch eine entity sein, obwohl er nur direkt als "Philosopher" eingetragen ist.

Außerdem lösen die unser SameAs Problem so, dass sie eine "Gruppeninstanz" definieren:
http://www.ontotext.com/owlim/owl-sameas-optimisation
Also sowas ähnliches was wir auch vorgehabt hätten. Die Frage ist nun nur noch, ob man auch direkt diese Gruppeninstanz querien kann.

Weiterhin scheint es kompatibel mit Sesame zu sein (bzw. sogar auf sesame zu beruhen):
http://owlim.ontotext.com/display/OWLIMv42/OWLIM-SE+Installation

Mein Vorschlag wäre, dass ihr OWLlim SE mal auf unserem testsystem installiert. Dann schickt ihr uns kurz wo wir Queries anfragen können (URL + kleiner Beispielquery). Dann probieren (Mathias und) ich mal aus, ob das System das tut, was es soll und wie ;-).

**Comment by sztyler** [comment]
we have to do this on a test server which is available by the end of the week

**Comment by jakob0910** [comment]
We installed owlim lite on osdorp.
