### ISSUE TITLE
Enhancer: Show three concepts at once

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#23]
Since there is enough space (due to the + button on the right of the area) for three concepts, I'd suggest to return to listing three concepts at once.

**Comment by sztyler** [comment]
Can you explain it in detail please - I'm not sure if I get what you mean

**Comment by mniepert** [comment]
In the concept field of the enhancer, there currently is only one concept
at a time visible (before clicking on the + button). However, it would be
better to see three concepts instead of just one at once (without having to
click on the + button).

**Comment by sztyler** [comment]
Ok - In fact there is a "preview" value which can be modified (default=1), but it is currently not implemented in the configuration interface. So I think what you want is already implemented.

The preview value determine how many properties/concepts should be displayed without clicking the plus symbol.

**Comment by mniepert** [comment]
Great! That's what I wanted.

**Comment by jakob0910** [comment]
I added the value which determines the preview scope to the setting interface (preview properties).
