### ISSUE TITLE
Linker: Different types of semantic links

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#26]
When dragging & dropping DBpedia objects, the pop-up dialogue that currently asks whether a sameAs link should be established should have a drop-down list with different possible types of semantic link. The sameAs link should be the standard selection.

Candidates for links should be:  owl:equivalentClass, is of rdf:type, has rdf:type, skos:related/brader/narrower, ...

**Comment by sztyler** [comment]
mm currently the linker is only visible if there is no sameAs relation - so it wouldn't be possible to create another relation like skos:related after the sameAs relation is established - does this make sense?

**Comment by mniepert** [comment]
Yes, but that shouldn't be a problem. For now, when the user clicks on the Dbpedia logo (when colored) there should just be an additional item in the popover that lists "establish additional links" or something like this leading the user to the linking interface.

**Comment by sztyler** [comment]
alright ;)

**Comment by sztyler** [comment]
implement first version in revision [master b22f0ae] - currently "is of rdf:type, has rdf:type" is missing. Furthermore there is no default value - the user has to choose something. I also add the new relation types to the enhancer relation dialog - hope this is ok? 

The Dialog works and stores the relation inside the tripple store but the "Relation Store" Page does not show currently all relations.

I changed a lot of stuff please check the new version of lode (server will be updated in a view minutes) and give me please some feedback. thx.

**Comment by mniepert** [comment]
> I also add the new relation types to the enhancer relation dialog - hope this is ok? 

Yes!

One more thing: In the linker interface, the drop-down with the relations should also list prefixes (e.g. owl:sameAs, etc.)

**Comment by sztyler** [comment]
sameas -> owl:sameAs
changed in revision [master 84151ec]

TODO
- check that the user can only create one sameAs Relation
- set default selection
- add is of rdf:type, has rdf:type

**Comment by jnoessner** [comment]
Related Issue: #53

**Comment by sztyler** [comment]
fixed/implemented in rev. 5f7f2d4

(server will updated within the next few days)
