### ISSUE TITLE
Buttons on start page too playful?

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#27]
I'm not 100% sure but I currently tend to think that "normal" more modest buttons would make the site appear more professional/academic. What do you think?

**Comment by jakob0910** [comment]
I share your opinion. These colorful buttons look also a bit fuzzy. I replaced them with normal buttons.

In general,  I think we should redesign the complete start page and add more information. The current one is not really a good entry point.

**Comment by sztyler** [comment]
I share your opinion too. Changes in Revision 18249f19 by Jakob.

**Comment by mniepert** [comment]
It looks better but I have one more suggestion:

Why not have one larger green button with "Explore content" (the height of the button should be the height of the current three buttons combined) and to its right two buttons for Help page and About the project?

**Comment by jakob0910** [comment]
I found a similar solution. I don't want to start to modify bootstrap elements at the moment.

**Comment by mniepert** [comment]
Right. Whatever is possible with bootstrap!
