### ISSUE TITLE
Linker: More... Button and Search field for link candidates

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#29]
Even with a high number of link candidates preset in the configuration file (e.g. 10) there are several cases where the right object is not listed despite being present in DBpedia. There are two suggestions/ideas I have at the moment to improve the situation:

(1) Add a search field where users can browse DBpedia entities (on click and without dynamically generating a list, this might pose some efficiency challenges).

(2) Add a "more" button. The content could be loaded in the background once the first X candidates are displayed.

This is just a suggestion though and I'm open for alternative idea.

**Comment by mniepert** [comment]
Example where this would be necessary:

http://linkedhumanities.com/link/dbpedia/thinker:t2463  (John Abercrombie)

**Comment by sztyler** [comment]
I think I will implement the second idea.

**Comment by sztyler** [comment]
completed in rev. 098156e6

(Now it is possible to browse through all available proposals - the proposals are sorted by weight (descending) - the proposals which have the same weight are ordered alphabetically)
