### ISSUE TITLE
[IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "" "]

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#3]
Examples:

http://drachten.informatik.uni-mannheim.de/link/dbpedia/thinker:t2910
http://drachten.informatik.uni-mannheim.de/link/dbpedia/entity:e16

Execution exception
[IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "" "]
In /opt/lode/app/utils/StringUtil.java at line 61.
58        String result = new String(s);
59
60        try {
61            result = URLDecoder.decode(s, "UTF8");
62        } catch(UnsupportedEncodingException e) {
63            e.printStackTrace();
64        }
65
66

**Comment by sztyler** [comment]
Is there any way to reproduce this problem?

**Comment by mniepert** [comment]
I'm not able to replicate the error because the URLs mentioned above return a weird page saying "error-no-person-bla". Not sure if that's because the URI doesn't exist anymore.

**Comment by sztyler** [comment]
please try to search the persons again

**Comment by mniepert** [comment]
It seems to work now (I found the entity for the id). The issue can be closed.

**Comment by sztyler** [comment]
I could reproduce this problem with another entity.

**Comment by sztyler** [comment]
fixed in revision [master dc58d31e]
