### ISSUE TITLE
How to set what string is displayed in "name" column in content explorer?

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#32]
What is displayed in the "Name" column of the content explorer list often depends on the type of the objects. For instance, for "Thinkers" this might be foaf:name but for journals this might be rdfs:label.

This is something that a user should be able to set up. The standard should probably be rdfs:label. (?)

**Comment by sztyler** [comment]
currently there is a set of properties which are ordered by priority - the programm check which properties are available and choose a property considering the prioritylist. I think Jakob will add this list to configuration page.

**Comment by mniepert** [comment]
Great. That's good. The list should contain

rdfs:label
foaf:name
skos:prefLabel

**Comment by sztyler** [comment]
Currently we use...
        uris.add("http://dbpedia.org/property/name");
        uris.add("http://www.w3.org/2000/01/rdf-schema#label");
        uris.add("http://xmlns.com/foaf/0.1/name");
        uris.add("http://dbpedia.org/property/alternativeNames");
        uris.add("http://dbpedia.org/property/id");
        uris.add("http://dbpedia.org/property/commonName");
        uris.add("http://www.w3.org/2004/02/skos/core#prefLabel");

**Comment by mniepert** [comment]
Great!

**Comment by jakob0910** [comment]
This feature is now configurable. [3caf4a0]

**Comment by sztyler** [comment]
can I close this issue?

**Comment by mniepert** [comment]
Yes, as far as I'm concerned.
