### ISSUE TITLE
Cannot open linker page

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#33]
I got the following error when i tried to link

http://linkedhumanities.com/link/dbpedia/inpho:turk_user

with my smartphone. (there was a very nice error handling around that error which suggested to write a ticket ;))

java.lang.NullPointerException at views.html.enhancers.link_entity$.apply(link_entity.template.scala:33) at views.html.enhancers.link_entity$.render(link_entity.template.scala:134) at views.html.enhancers.link_entity.render(link_entity.template.scala) at controllers.enhancers.MainController.link(MainController.java:45) at Routes$$anonfun$routes$1$$anonfun$applyOrElse$29$$anonfun$apply$29.apply(routes_routing.scala:401) at Routes$$anonfun$routes$1$$anonfun$applyOrElse$29$$anonfun$apply$29.apply(routes_routing.scala:401) at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:141) at play.core.Router$Routes$$anon$1.invocation(Router.scala:322) at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:31) at play.GlobalSettings$1.call(GlobalSettings.java:63) at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:74) at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:73) at play.libs.F$Promise$PromiseActor.onReceive(F.java:420) at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) at akka.actor.ActorCell.invoke(ActorCell.scala:386) at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) at akka.dispatch.Mailbox.run(Mailbox.scala:212) at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502) at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by sztyler** [comment]
fixed in revision [master c5b5304]
