### ISSUE TITLE
Improve Enhancer Interface

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#36]
When dragging & dropping a concept/property/property value the status of the three boxes (concepts, data properties, object properties) should be stored and restored after the operation is performed. Status here means (a) whether the +-button has been pressed to extend the box, (b) whether the "load more" button been pressed to load all of the concepts/properties, (c) the position of the window from where the user has dragged the property/concept from, the window should scroll back to this position.

Moreover, when a concept/property/property value has been dragged & dropped it should disappear from the right (i.e., dbpedia) side of the window. This works (most of the time) for data and object properties but not yet for concepts.

**Comment by sztyler** [comment]
fixed/implemented in rev. 01761a4a

(server will updated within the next few days)

**Comment by jnoessner** [comment]
Almost ;-).

For http://lode.informatik.uni-mannheim.de/enhance/entity:e10/dbpedia we have two times 'wiki page i d'.

**Comment by sztyler** [comment]
fixed in rev. 879fc7fc
