### ISSUE TITLE
[QueryExceptionHTTP: Bandwidth Limit Exceeded]

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#4]
Occurs frequently.

Execution exception
[QueryExceptionHTTP: Bandwidth Limit Exceeded]
In /opt/lode/app/sparqlcontrollers/Sparql.java at line 24.
21    {
22        QueryExecution qexec = Sparql.prepare(request, destination);
23
24        ResultSet results = qexec.execSelect();
25        List<QuerySolution> result = ResultSetFormatter.toList(results);
26        qexec.close();
27
28        return result;
29    }

**Comment by sztyler** [comment]
QueryExceptionHTTP error page redesgined (see attachment)
![errorPage](https://f.cloud.github.com/assets/3532545/156841/46e283f8-76aa-11e2-97c4-06b5a637e163.png)

fixed in master 24e44f1
