### ISSUE TITLE
Changing "Values per properties" for the Linker doesn't work

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#40]
Changing "Values per properties" for the Linker doesn't work. 

I set the value from 3 to 4 but only 3 values where shown even though there are more.

**Comment by sztyler** [comment]
I will check if this is a mistake of the configuration interface or the method itself.

**Comment by jakob0910** [comment]
The configuration interface works correctly.

**Comment by sztyler** [comment]
fixed in revision [master f4b25a2]
