### ISSUE TITLE
"Select all" option for property values

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#41]
When the user drags & drops a property there should be an "Select all values" option in the pop-up. Examples where this is necessary is the "influenced by" property for philosophers where it is not uncommon for a thinker to have dozens of influences.

**Comment by sztyler** [comment]
I know that there could be a lot of values but if I add a "Select all" function this could lead to the problem that the user does not check the values which he/she wants to add - even if there are less values. Hence the error rate will increase (e.g. if the data source provides data with mistakes then it is less probably that the user noticed these mistakes)

**Comment by mniepert** [comment]
Agreed (for now). Then let's rephrase the issue:  When a property with lots of values is dragged and dropped, the user should have a scrollable list in the verification pop-up with each value having a checkbox. Currently, its' only at most 5 values at once. Also, this is a subtle issue: When a property is dragged (either object or datatype) it should still be shown on the DBpedia side as long as it has values on the DBpedia side that are not on the local side.
