### ISSUE TITLE
Dragging & Dropping data and object properties (behavior)

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#46]
When a property with lots of values is dragged and dropped, the user should have a scrollable list in the verification pop-up with each value having a checkbox. Currently, its' only at most 5 values at once. Also, this is a subtle issue: When a property is dragged (either object or datatype) it should still be shown on the DBpedia side as long as it has values on the DBpedia side that are not on the local side.

**Comment by sztyler** [comment]
fixed/implemented in rev. d8e25147

(server will updated within the next few days)
