### ISSUE TITLE
screenshots overlap w/text on help page

### ISSUE THREAD

**Issue by JaimieMurdock** [linkedhumanities/lode#47]
on the help page, the screen shots are overlapping with the text, need more padding.
http://www.linkedhumanities.com/help

using Chrome on Ubuntu, should be the same in all WebKit-based browsers.

**Comment by mniepert** [comment]
Thanks Jaimie! By the way, we have noticed that Chrome is currently
incompatible with some of the JavaScript features on the site. We are
currently working on fixing this.

**Comment by mniepert** [comment]
Timo & Jakob: Considering the mounting evidence that LODE is incompatible with Chrome both in terms of the deisgn (padding etc.) and the functionality (JavaScript, pop-overs, etc.) this should have a relatively high priority. Chrome (and Chromium etc.) is a very popular browser.

**Comment by sztyler** [comment]
We know that and we will try to handle these problems. thx for your feedback.

**Comment by jakob0910** [comment]
Fixed in revision 81a887b7.
