### ISSUE TITLE
[IndexOutOfBoundsException: Index: 0, Size: 0]

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#5]
http://drachten.informatik.uni-mannheim.de/link/dbpedia/thinker:t3738

Execution exception
[IndexOutOfBoundsException: Index: 0, Size: 0]
In /opt/lode/app/utils/ResUtil.java at line 101.
98
99        // store the most frequent properties
100        for(int i = 0; (i < numLit && i < numRes) || i < sortedProperties.size(); i++) {
101            PropertyContainer pair = sortedProperties.get(i);
102            Map<String, HashSet<String>> values = new LinkedHashMap<String, HashSet<String>>();
103
104            // counter for number of values
105            Integer counter = new Integer(0);
106

**Comment by sztyler** [comment]
should be fixed in master 24e44f1
