### ISSUE TITLE
Display Only Instances as Linking Canidates

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#51]
I discovered that sometimes concepts (might also be properties) are suggested as linking canidates. One example are the linking canidates for 'platonism' http://www.linkedhumanities.com/link/dbpedia/entity:e443. One of the link suggestions is actually a property. 

We have to make sure (change Sparql query) that only instances are displayed as possible canidates for same-as links.

**Comment by sztyler** [comment]
fixed in rev. c5cbeb3

(server will updated within the next few days)
