### ISSUE TITLE
Simplify 'Create Relation' Window

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#53]
First: SameAs is only for INSTANCES, not for properties or concepts. Here, we have to use owl:equivalentClass and owl:equivalentProperty (depending what the user chose).

The create relation window is too complicated. 

My suggestion would be something like (example):
## Create Relation

thinker     is the same as     Person

If the user hovers over thinker he gets the URI (e.g. http://inpho.co....). Same for person. If he hovers over 'is the same as' he gets 'owl:equivalentClass'. 'is the same as' is a selection box where the users can also select the following:

owl:disjointWith : completely different from
owl:equivalentClass or owl:equivalentProperty : is the same as
skos:related: is related to
skos:broarder: is broarder than
skos:narrower: is narrower than

Please also check the 'add new value' window. Here, we should also hide the exact URI from the user and show them only if he hovers over it.

**Comment by sztyler** [comment]
fixed/implemented in rev. 5f7f2d4

(server will updated within the next few days)
