### ISSUE TITLE
No names given for any ideas?

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#56]
Is it correct that Ideas have no 'name' attribut? I am asking because I remember that they once had names and because at inpho (https://inpho.cogs.indiana.edu/idea) they also have names.

**Comment by jnoessner** [comment]
I just figured out that the entities strangely have names that seems to be ideas (e.g. http://lode.informatik.uni-mannheim.de/content/entity/entity%3Ae1002). Maybe this is related to the same-as clustering problem?

**Comment by jakob0910** [comment]
The inpho rdf file which I use does not have a same relation to an idea for entity:e1002. If I add the triple "entity:e1002 owl:sameAs idea:idea1002", the name is also shown for the idea entry. The problem will be solved when we upgrade the backend to OWLIM Lite (or SE) with the owl horst reasoner.

We should clarify what the correct/current inpho rdf file is.

**Comment by jakob0910** [comment]
This problem should be handled in a newer version of the rdf file. You should consider this in your request.
