### ISSUE TITLE
Nicer Link-Delete Interface

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#59]
For link deletion, the interface is a little bit unintuitive and 'not so pretty'. Is it possible to just have a popup like the one when we establish a link in the linker interface? 

After deletion of the link I am not redirected to the page, where I have been before.

**Comment by jakob0910** [comment]
Now, the delete page can only be accessed from the "show entity" page. The user gets redirected to this page in any case. This was not possible before as there was also a direct link from the content explorer to this page.

In my opinion, this interface is nice enough for now. We can change it later when more important tasks are finished.
