### ISSUE TITLE
Bug (Exception)

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#61]
http://www.linkedhumanities.com/enhance/thinker:t2585/dbpedia

Execution exception

[QueryParseException: Lexical error at line 1, column 177. Encountered: "\'" (39), after : "Communism"]
In /opt/lode/app/sparql/Sparql.java at line 90.

87        request = StringEscapeUtils.unescapeHtml(request);

88        request = request.replace("\n", "\n"); // TODO WORKAROUND

89

90        Query sparqlQuery = QueryFactory.create(request);

91        QueryEngineHTTP qexec = QueryExecutionFactory.createServiceRequest(endpoint.getDestination(), sparqlQuery);

92

93        if(Settings.DEFAULTGRAPH.containsKey(endpoint)) {

94            qexec.addDefaultGraph(Settings.DEFAULTGRAPH.get(endpoint));

95        }

**Comment by sztyler** [comment]
fixed in rev. f4ae806

problem was that the "isURI" method does not classify a string with spaces correctly - furthermore the spaces were not correctly encoded.
