### ISSUE TITLE
Guide Through Menue

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#62]
I tested a few links and enhancements and I noticed that the menu is still a little bit unintuitive. 

My suggestion would be, to remove the gray and colored dbpedia symbol (because it now seems to be sure that we will focus on dbpedia!).

Instead I would introduce small buttons saying 'view', 'link', 'enhance', 'delete',  'extern'. I leave it to your creativity to design nice buttons or to just put the text on buttons. Of course a small more detailed text, when mouseover, would be nice.

In search Interface:
- if there is a link: show all five
- if not: show only 'view' and 'link' 

In view Interface:
- if there is a link: show  'link', 'enhance', 'delete',  'extern'
- if not: show only 'link' 

In linker Interface:
- Show in the upper right either 
  - only 'view' button (if no link is established) or
  - 'view', 'enhance', 'delete',  'extern' if link is established.

In enhancer Interface (upper right):
- Show 'view', 'link', 'delete',  'extern'

What do you think? This might be more intuitive than it is now, or?

**Comment by sztyler** [comment]
Is it clever to drop the possibility to add other endpoints in the future? I am not convinced.

**Comment by jnoessner** [comment]
We would not drop the opportunity. If we want to add other endpoints, we would load the different endpoint REPLACING DBPedia (this selection could be made in some configuration file).

**Comment by mniepert** [comment]
My opinion is to leave it as it is right now. Creating new buttons and changing the interface is something we shouldn't do at this point. Also, I still think it would be nice to have the possibility of several external sources at once.

**Comment by jnoessner** [comment]
Maybe later.
