### ISSUE TITLE
Show sameAs on left side

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#63]
In addition to "type" and "name" it would be nice to include a section "sameAs" where all the equivalent entities in BDpedia would be listed. This should be easy to do and query for since it's in the local repo.

**Comment by jnoessner** [comment]
There is only one same-as to dbpedia, or? And it is implicitly displayed by the colored dbpedia symbol. Do you want that the user gets the exact URI of the same-as link?

**Comment by sztyler** [comment]
It is simple - should I implement this?

**Comment by mniepert** [comment]
In addition to it being explicitly visible to the user, it would allow
several sameAs links and, in addition, it could be extended in the future
to also include other links that users can generate (related to,
differentFrom, disjoint, etc.)

So, yes, I think it's a good idea.

**Comment by sztyler** [comment]
done in rev. b5fb7875

**Comment by mniepert** [comment]
When a link is created via drag&drop, the content of the sameAs list should be updated.

**Comment by sztyler** [comment]
fixed in rev. f8334d9
