### ISSUE TITLE
Previous button causes error message

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#64]
http://linkedhumanities.com/content

Search for "Kant", move to the second page and click on "previous":

"You cannot load a page smaller than 1"

**Comment by sztyler** [comment]
I can reproduce this problem on linkedhumanities.com but the problem does not occur with my local version lode (tested with firefox and chrome, windows)  - I will check this again after the LODE Server was updated.

**Comment by sztyler** [comment]
this problem still exists

**Comment by jakob0910** [comment]
This problem is fixed.
