### ISSUE TITLE
Minor: Select everything when enhancing (data) property

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#65]
When I enhance a data and object property non of the values (the assertions) are selected. Especially when there is only one value, it was quite anoying to select the value each time. Would it be possible to select everything?

**Comment by sztyler** [comment]
It would be possibly but it is intended that the values are not selected by default because the user should "confirm" what he wants to add. (This can be compared to something like "do you really want to leave the game?")

other opinions?

**Comment by jnoessner** [comment]
Ok, then just mark everything if there is only one value. Because in that case it is really anoying to mark this one entry every time: If there is only one entry, its more or less clear that the user wants to enhance the property together with this one value.

**Comment by sztyler** [comment]
fixed in rev. 99a84ca
