### ISSUE TITLE
Stuck when enhancing object property with several values

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#66]
How to reproduce the problem:

Go to enhancer interface for a thinker that has the object property "subject" with several values. Drag and drop "subject" to "add new object property". Select several entries and click on enhance. The pop-up never closes and the user is stuck. The values are actually added once the interface is reloaded.

**Comment by sztyler** [comment]
does not appear in rev. a9e515ae (tested with the properties "subject" and "wiki page external links" added more then 20 values for each property at once - instance: "Plato").

Note: It is possible that it takes up to one second to insert "one" value in the database. The speed also depend from the speed of the own internet connection

**Comment by mniepert** [comment]
This is still a problem. It is stuck indefinitely.

**Comment by sztyler** [comment]
ok - I will check it again

**Comment by mniepert** [comment]
bump...

**Comment by sztyler** [comment]
I already localized the problem. It is an nullpointer in the java script part (this is independet of the number selected values). This problem does not influence any other part. I will fix it at the end of the week. 

Thx for the reminder :)

**Comment by sztyler** [comment]
fixed in rev. 74c9dae
- development system will be updated during the next two hours
- stable system will be updated during the next week

**Comment by mniepert** [comment]
This is where I wanted to write this.  The weird thing is that this only happens for "object properties" and it happens even if only one single value is added. The problem is probably rooted in the query which is specific for object properties.

**Comment by mniepert** [comment]
This is not a problem on the development server. So I assume the stable server hasn't been updated. Ignore the previous messages.

**Comment by sztyler** [comment]
Stable Server will be updated tomorrow ;)
