### ISSUE TITLE
"Loading content"  problem when unselecting all concepts 

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#69]
I type something and then unselect all filters; it hangs with "loading content".  E.g., type “thea” and then unclick “inpho:entity” and all other concepts.

Reported by Cameron.

**Comment by jakob0910** [comment]
I refactored the content explorer and the initial problem should be fixed.

However, the server (at least osdorp) seems to have performance issues if we send to many query simultaneously as we get many socket timeout exceptions. This is kind of strange because everything runs relatively good on my notebook which is relatively old and slow...

**Comment by mniepert** [comment]
The weird thing is that this only happens for "object properties" and it happens even if only one single value is added.  The problem is probably rooted in the query which is specific for object properties.

**Comment by jakob0910** [comment]
Is your commend related to this ticket?

If yes: Can you provide an example? I am pretty sure that the query is not the problem as the described problem does not occur on my PC or Notebook. We get a lot of timeouts if we send too many complex queries to our local sparql endpoint (owlim).

**Comment by mniepert** [comment]
Sorry wrong ticket...

**Comment by jakob0910** [comment]
Ok, but what's your opinion on this one? There are two possible solutions as it is very unlikey that we get better hardware:
1. We accept the problem.
2. After a user select/unselects a type he has to wait until the result is returned before another type can be selected/unselected.

**Comment by mniepert** [comment]
I think for now (1.) is OK. However, note that this is related to #72 . At the moment, the message 

"There are no concepts which match the query."

is displayed correctly after a while but the "loading content" for the entities remains indefinitely.

**Comment by jakob0910** [comment]
Tickets #71, #72 are already fixed. I will close these tickets tomorrow after we updated the server.

**Comment by mniepert** [comment]
Nice.
