### ISSUE TITLE
Delete property-value-pair page pop-up problem

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#70]
weird error popup (with message "...") when deleting a link through the hoverover on DBpedia icon ("remove link")

**Comment by sztyler** [comment]
This is a debug message regarding the "History Back" function - the sameAs link will be deleted

**Comment by jakob0910** [comment]
Now, the delete page can only be accessed from the "show entity" page. The user gets redirected to this page in any case. This was not possible before as there was also a direct link from the content explorer to this page.
