### ISSUE TITLE
Creation of "related to" link problem

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#73]
When a "is related to" link is created with the linker interface, the name and URI of the relation are weird:

Name:   null
URI:       file:///opt/lode/null

This should be (in this case) 

name:  SKOS:related
URI: http://www.w3.org/2004/02/skos/core#related

**Comment by mniepert** [comment]
This problem should be checked and solved in general. It probably also occurs for other link types.

**Comment by sztyler** [comment]
confirmed

**Comment by sztyler** [comment]
fixed in rev. c3e5f15
- development system will be updated during the next two hours
- stable system will be updated during the next week
