### ISSUE TITLE
Remove link

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#74]
Links should be removable also from the "overview" page of entities. Currently, one can only remove sameAs links.

**Comment by sztyler** [comment]
Do you mean links like...(these are only examples)

http://inpho.cogs.indiana.edu/thinker http://www.w3.org/2002/07/owl#disjointWith http://dbpedia.org/class/yago/AncientGreekPhilosophers
http://xmlns.com/foaf/0.1/name http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.w3.org/2000/01/rdf-schema#label
http://purl.org/dc/terms/subject http://www.w3.org/2002/07/owl#inverseOf http://www.w3.org/ns/prov#wasDerivedFrom

... currently we have no overview for deleting "global" relations e.g. between properties. -they are independet of the instances like Plato to they should be administered somewhere else.

Any suggestions how and where this new overview should be added?

**Comment by mniepert** [comment]
No, I mean relations between individuals (not properties). For instance,
let's say we create a "is related to" link between Aristotle's_Aesthetics
(the book) and Aristotle's_Aesthetics (the inpho idea).

Now, let's assume we want to remove this link. We cannot until we create a
sameAs link, because only then do we have access to the enhancer interface.

**Comment by sztyler** [comment]
in fact, in the current version it is not possible to define skos:related in the linker interface

see https://github.com/linkedhumanities/lode/issues/67#issuecomment-22822141

but the problem would still exists for owl:differentFrom - so I think the best solution is to improve the deletion-page which is actually used for the owl:sameas relation (relations which are created on the linker page are depending on the chosen instance)

**Comment by mniepert** [comment]
right (even though, it is possible in the linker at the moment, it creates the null relation which I mentioned in a different issue). That's how I noticed this problem: I wanted to remove the "null" link but it was not possible unless I first created a sameAs link.

**Comment by sztyler** [comment]
@OffTopic
This problem only exists on lode.informatik.uni-mannheim.de / http://linkedhumanities.com/ (Stable Server) - the Stable Server is outdated - this problem is already fixed on osdorp.informatik.uni-mannheim.de:9000/ (Dev Server). Stable Server will be updated during the next week.

@Task
Enhance sameAs deletion page

**Comment by jakob0910** [comment]
Now you are able to delete links of the types owl:sameAs and owl:differentFrom. I can extend this list if necessary but these are the only one you can add at the moment. You are also able to delete links if no same as relation exists.
