### ISSUE TITLE
ToolTip Issues

### ISSUE THREAD

**Issue by sztyler** [linkedhumanities/lode#75]
TODO (known issues)
- some tooltips do not disappear
- sometimes the tooltip does not appear - only the html code is visible
- remove clickable tooltips from content explorer (1)
- link in tooltip should be underlined when mouse is over
- tooltip should not disappear if the mouse is over

(1) We (Jakob and me) are thinking that it is overstated that the tooltips are clickable on the content explorer page. For instance, all properties (mouse over a string in the name column). What do you (Mathias -it was your request) thinking?

**Comment by mniepert** [comment]
It's not high priority.

**Comment by sztyler** [comment]
sure - I only want to remark these points - actually I think that I don't solve this issue this year.

**Comment by sztyler** [comment]
fixed in rev. master d4495356
