### ISSUE TITLE
Linker interface -- types of links

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#77]
Why did you decide against having several types of links in the linker interface. The problem as it is right now, is that you can only create "sameAs" and "differentFrom" links. But what if you want to create a "skos:relatedTo" link? Is there a problem with having this functionality?

**Comment by sztyler** [comment]
Hi
It would be no problem to add e.g. skos:relatedTo to the Linker but... 

A few month ago, you create this ticket...
https://github.com/linkedhumanities/lode/issues/67

I investigate some time in this issue and noticed that skos:xyz is only conform with concepts not with instances. So I removed it from the Linker page....and nobody raise a plea after I wrote it in issue #67. So....if your are thinking that this is wrong then let me know :)

Source
http://www.w3.org/TR/skos-reference/#semantic-relations
(Quote: "The property skos:related is used to assert an associative link between two SKOS concepts.")

**Comment by mniepert** [comment]
This relates to a deeper questions about the (often ambiguous) distinction
between instances and concepts. For instance, what is dbpedia:animal? Is it
a concept or an instance? I would say it is the former. And what about
inpho:philosophyOfMind? I think the assumption that we only need to create
links between instances in the linker is too restrictive. It should be up
to the user what relations are offered in the linker interface.

**Comment by mniepert** [comment]
Just to be clear: #67 was about the enhancer not the linker.

**Comment by mniepert** [comment]
The enhancer can stay the way it is right now.

**Comment by sztyler** [comment]
Ok - I will extend the Linker with the skos:xyz vocabulary

(but #67 has also the tag "Linker" ;))

**Comment by mniepert** [comment]
This should be something in the configuration section. There should
definitely be an admin interface for this.

**Comment by sztyler** [comment]
You mean a configuration interface to define which relations are displayed on the Linker page?

**Comment by mniepert** [comment]
Yes.

**Comment by sztyler** [comment]
complete in rev. master 63529a73.

Now it is possible to define in the configeration section which relations should be displayed on the Linker or Enhancer page.
