### ISSUE TITLE
Search also for concepts

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#82]
Search for concepts with
concept:Philosopher Pluto

**Comment by jakob0910** [comment]
Done.

**Comment by mniepert** [comment]
Would it be difficult to have autocomplete functionality?  So when one
types the possible concept names are displayed...

**Comment by jnoessner** [comment]
Works great. It filters concepts and instances while typing... nice!

**Comment by jnoessner** [comment]
Now I noticed a bug / feature. When I search for 

```
concept:sophy qual
```

it displays me (among others)

```
:inverted_qualia    inverted qualia     Idea, qualia, philosophy_of_mind, consciousness
```

However, if I now search for 

```
concept:sophy inverted qual
```

results are empty.

The search 

```
 concept:sophy inverted_qual
```

then returns the actual instance. Are you taking the uri for search?

**Comment by jakob0910** [comment]
@mniepert I integrated an autocomplete functionality.

@jnoessner The behavior is correct. The name column shows the last part of the URI as the dataset does not provide a label/name. You may have noticed that the value in the name column has no toolip that usually shows the used property.

However, we search the subject and object with query. In your example, we have only the URI (http://www.owl-ontologies.com/unnamed.owl#inverted_qualia) that matches the query. Thus, it you need the "_" character to find the instance.

**Comment by mniepert** [comment]
Great, I like the autocomplete functionality a lot. It almost renders the
"concept:bla" functionality obsolete.
