### ISSUE TITLE
Create possibility to delete links and assertions

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#9]
Users should be able to delete links and enhancements. However, this does not have the highest priority right now!

**Comment by mniepert** [comment]
Note: The options to delete stuff should be located in the entities overview page.

**Comment by sztyler** [comment]
I was not sure to implement this on the enhancer page or the entities overview page because if someone enhance something an he/she noted that he/she makes a mistake then he/she has to browse to enhancer page only to fix the mistake... what do you think?

**Comment by mniepert** [comment]
Hm, good question. I'm worried that the enhancer interface will get too crowded. But you are right, there should be an "undo" option or something like that.

**Comment by mniepert** [comment]
What about one trash can field/button where entities can be dragged to?

**Comment by sztyler** [comment]
Yea I'm sharing the worries... In fact I had exaclty the same idea regarding the trash field/symbol - but I'm currently not sure If I can handle this regarding the states which have to be considered if I move an value/property (the javascript grows and grows...) - I will investigate some time during this week in this problem.

**Comment by jnoessner** [comment]
What if in any detailed view we place a small red cross next to the source fact, where it can be deleted. Then this would be equal for any existing view.

**Comment by jnoessner** [comment]
So in both, the enhancer and the viewer.

**Comment by jnoessner** [comment]
And we could later extend that feature with ie a rename function. If too many red crosses are too ugly they could appear only when mouse is over the text.

**Comment by jnoessner** [comment]
Or be gray and become red ;)

**Comment by sztyler** [comment]
I don't like the idea of a lof of red buttons because the will lead crowded page - I prefer the idea with the wastebin symbol

**Comment by jnoessner** [comment]
Summary: Open issues: (1) Implement delete link command for linker (2) Implement trash symbol for enhancer.

**Comment by sztyler** [comment]
Status: In Progress
Currently I implement the possibility to delete properties/values of a local instance.

**Comment by sztyler** [comment]
delete properties/values (enhancer)

> completed in rev. 3a4d4bc (Timo)

delete sameAs Relation

> completed in rev. 6db31245 (Jakob)

please create a new ticket for the management of relations like "abc skos:related def"
